### PR TITLE
Bug fixes km

### LINKED ISSUE #103: Pass existing guest list to `GuestList` from ???
where should we store data initially retrieved from API calls? how are they passed to child components properly?

### LINKED ISSUE #105: BUG: dates for weddings:
- [ ] can't add a wedding that is today's date, 
- [ ] wedding for 1/15 on all weddings page comes up as 1/16 on details page

### LINKED ISSUE #106: Bug: form submissions update API but won't show up on DOM until refreshing page
- [ ] guests added -> guestlist check boxes
alternative bug:
infinite loop with useEffect + async function

### PR DESCRIPTION
**Pull request by Kristiannmiller**
# Pull Request

## What's this PR do? 

- [X] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Testing
- [X] Styling
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Description of changes?
- Fixes refresh bugs in VendorDashboard, GuestList, and PhotoList components
- Fixes date bugs in VendorDashboard, AddWeddingForm, and WeddingDetails components
- Fixes scrolling bug when changing views in WeddingDetails
- Removes LandingPage path (temporary until we get the page done so that on our deploy it goes straight to VendorDashboard view)
- Changes routing to default '/' path when clicking the logo at the top of the page
- Adds error handling message to VendorDashboard to avoid compiling error if no weddings are stored.
- Adds styling to error handing message in VendorDashboard

## Any background context you want to provide? 
We can change the way the error handling works if we want. Mainly just wanted to get that big error out of the way so we could avoid the LandingPage and still get a VendorDashboard to render.

## What are the relevant tickets? 
* Addresses #15 
* Closes #105 
* Closes #106 
* Closes #103

### CODE REVIEW

File: src/components/AddWeddingForm/AddWeddingForm.tsx [hunk 1]
```diff
@@ -2,33 +2,40 @@ import React, { useState } from 'react';
...
 
   const [name, setName] = useState('')
   const [email, setEmail] = useState('')
   const [date, setDate] = useState('')
   const [image, setImage] = useState('')
 
-  const submitWedding = (event: React.FormEvent) => {
+  const submitWedding = async (event: React.FormEvent) => {
     event.preventDefault();
+    const weddingDate = dayjs(date).format('MM/DD/YYYY')
```
Comment (ericberglund117) [inline src/components/AddWeddingForm/AddWeddingForm.tsx:30]: I see what you did here. I'm glad it works! Nice thinking

File: src/components/App/styledComponents.styles.ts [hunk 2]
```diff
@@ -196,6 +200,8 @@ export const StyledCard = styled.section<StyledCardProps>`
     height: ${props => {
       if(props.contents === 'list') {
         return '75%;'
+      } else if(props.contents === 'fullPage') {
+        return '25%;'
       } else {
         return '80%;'
```
Comment (ericberglund117) [inline src/components/App/styledComponents.styles.ts:206]: This is such a cool way to make the design responsive!

**Review by ericberglund117 — APPROVED** [review]

File: src/apiCalls.tsx [hunk 3]
```diff
@@ -28,7 +28,7 @@ export const postAWedding = (wedding: any) => {
   })
   .then(response => {
     if(response.ok) {
-      return response
+      return response.json()
```
Comment (hannakim91) [inline src/apiCalls.tsx:31]: Was this part of what was leading to some bugs?

File: src/components/AddWeddingForm/AddWeddingForm.tsx (hunk 1 above)
Comment (hannakim91) [reply src/components/AddWeddingForm/AddWeddingForm.tsx:30]: Good catch!!

File: src/components/App/App.tsx [hunk 4]
```diff
@@ -23,14 +25,22 @@ const App = () => {
...
+
   useEffect(() => {
     const allWeddings = async () => {
       const result = await getWeddings()
       if(result.length > 0) {
         result.forEach((wed: any) => {
-          wed.date = new Date(wed.date)
+          wed.date = dayjs(wed.date)
+        })
+        console.log(result)
```
Comment (hannakim91) [inline src/components/App/App.tsx:39]: We should clean up `console.logs` at some point

File: src/components/App/App.tsx [hunk 5]
```diff
@@ -23,14 +25,22 @@ const App = () => {
...
+        let sortedResult = result.sort((a: any, b: any) => b.date - a.date)
+        let sortedWeddings = sortedResult.forEach((wedding: any) => {
+          wedding.date = dayjs(wedding.date).format('MM/DD/YYYY')
```
Comment (hannakim91) [inline src/components/App/App.tsx:42]: Nice work fixing these date bugs using dayjs!

File: src/components/App/App.tsx [hunk 6]
```diff
@@ -43,16 +53,11 @@ const App = () => {
   return (
     <div className="appWrap">
       <header className="headerWrap">
-        <Link to={`/vendor-dashboard`}>
+        <Link to={`/`}>
```
Comment (hannakim91) [inline src/components/App/App.tsx:56]: I think this is a good call to reduce unnecessary page navigation for now

File: src/components/GuestList/GuestList.tsx [hunk 7]
```diff
@@ -107,6 +100,8 @@ const GuestList: React.FC<WeddingData> = ({
     setGuests(filteredGuestList)
   }
 
+  useMemo(() => setGuests(guestList), [guestList])
```
Comment (hannakim91) [inline src/components/GuestList/GuestList.tsx:103]: I'll have to learn more about how this hook works!

**Review by hannakim91 — APPROVED** [review]
Thanks for the additional work! Looking forward to next steps.

File: src/components/App/styledComponents.styles.ts (hunk 2 above)
Comment (Kristiannmiller) [reply src/components/App/styledComponents.styles.ts:206]: Styled components are awesome!

File: src/apiCalls.tsx (hunk 3 above)
Comment (Kristiannmiller) [reply src/apiCalls.tsx:31]: It was part of it for sure. We were originally adding the newest wedding to the weddings on the dashboard using a date.now id, so when we clicked on the wedding it was getting an error because the id didn't exist in the database until the page was refreshed and the date.now id was replaced by the id created in the backend.

File: src/components/GuestList/GuestList.tsx (hunk 7 above)
Comment (Kristiannmiller) [reply src/components/GuestList/GuestList.tsx:103]: I'm a little unclear of how it works exactly too, but I can definitely attempt to explain, and we can investigate it a bit more

File: src/apiCalls.tsx (hunk 3 above)
Comment (hannakim91) [reply src/apiCalls.tsx:31]: Thanks for the clarification!
