### PR TITLE
Bug fix eb

### LINKED ISSUE #115: Re-route to VendorDashboard after adding a wedding

### PR DESCRIPTION
**Pull request by ericberglund117**
# Pull Request

## What's this PR do? 
- display weddings in chronological order on Vendor Dashboard
- After a user submits a wedding, they are now SUCCESSFULLY routed back to Vendor Dashboard. 

- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Testing
- [ ] Styling
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Description of changes?
- Added history to AddWeddingForm component in order to route back to the homepage after submitting a wedding

## Any background context you want to provide? 
- tried working around event.preventDefault
- tried working around mounting and unmounting a component 
- success using history 

## What are the relevant tickets? 
* Addresses
* Closes #115

### CODE REVIEW

File: src/components/App/App.tsx [hunk 1]
```diff
@@ -38,17 +38,17 @@ const App = () => {
           wed.date = dayjs(wed.date)
         })
         console.log(result)
-        let sortedResult = result.sort((a: any, b: any) => b.date - a.date)
+        let sortedResult = result.sort((a: any, b: any) => a.date - b.date)
```
Comment (Kristiannmiller) [inline src/components/App/App.tsx:41]: Thanks for catching this! Dates are confusing

File: src/components/AddWeddingForm/AddWeddingForm.tsx [hunk 2]
```diff
@@ -36,8 +38,8 @@ const AddWeddingForm: React.FC<Props> = ({
     }
     const response = await postAWedding(newWedding);
     addNewWedding(response);
-    // should be a POST request + adding card to UI
     clearInputs();
+    history.push('/')
```
Comment (hannakim91) [inline src/components/AddWeddingForm/AddWeddingForm.tsx:42]: I think this helps with the user experience - being able to be routed back to the main page after they add a wedding

**Review by hannakim91 — APPROVED** [review]
